import { Navigation } from "@/components/navigation"
import { Footer } from "@/components/footer"
import { AlertTriangle } from "lucide-react"

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen flex flex-col">
      <Navigation />
      
      <main className="flex-1 pt-20">
        <section className="max-w-3xl mx-auto px-6 py-24">
          <span className="text-xs uppercase tracking-widest text-muted-foreground">
            Important Notice
          </span>
          <h1 className="font-serif text-4xl md:text-5xl leading-tight text-foreground mt-4">
            Disclaimer
          </h1>
          
          <div className="mt-12">
            {/* Important Notice Box */}
            <div className="p-6 bg-secondary border border-border rounded-sm mb-12">
              <div className="flex items-start gap-4">
                <AlertTriangle className="w-5 h-5 text-accent flex-shrink-0 mt-0.5" />
                <div>
                  <h2 className="font-medium text-foreground mb-2">
                    Luma is not therapy, diagnosis, or treatment.
                  </h2>
                  <p className="text-sm text-muted-foreground leading-relaxed">
                    This experience is designed for general reflection and self-awareness 
                    purposes only. It does not provide medical advice, mental health 
                    treatment, or professional counseling.
                  </p>
                </div>
              </div>
            </div>

            <div className="space-y-12">
              <div>
                <h2 className="font-serif text-xl text-foreground mb-4">
                  Nature of the experience
                </h2>
                <p className="text-muted-foreground leading-relaxed">
                  Luma is a reflective experience that uses image selection and AI-generated 
                  text to surface patterns for your consideration. The reflections provided 
                  are interpretive descriptions, not clinical assessments or diagnoses.
                </p>
              </div>

              <div>
                <h2 className="font-serif text-xl text-foreground mb-4">
                  Not a substitute for professional care
                </h2>
                <p className="text-muted-foreground leading-relaxed">
                  If you are experiencing mental health difficulties, emotional distress, 
                  relationship problems, or any condition that affects your wellbeing, 
                  please seek support from a qualified mental health professional, counselor, 
                  or therapist.
                </p>
                <p className="text-muted-foreground leading-relaxed mt-4">
                  Luma does not replace:
                </p>
                <ul className="mt-4 space-y-2 text-muted-foreground">
                  <li className="flex items-start gap-3">
                    <span className="w-1.5 h-1.5 rounded-full bg-muted-foreground mt-2 flex-shrink-0" />
                    <span>Professional mental health assessment or diagnosis</span>
                  </li>
                  <li className="flex items-start gap-3">
                    <span className="w-1.5 h-1.5 rounded-full bg-muted-foreground mt-2 flex-shrink-0" />
                    <span>Psychotherapy, counseling, or psychiatric treatment</span>
                  </li>
                  <li className="flex items-start gap-3">
                    <span className="w-1.5 h-1.5 rounded-full bg-muted-foreground mt-2 flex-shrink-0" />
                    <span>Couples therapy or relationship counseling</span>
                  </li>
                  <li className="flex items-start gap-3">
                    <span className="w-1.5 h-1.5 rounded-full bg-muted-foreground mt-2 flex-shrink-0" />
                    <span>Medical advice or treatment of any kind</span>
                  </li>
                </ul>
              </div>

              <div>
                <h2 className="font-serif text-xl text-foreground mb-4">
                  AI limitations
                </h2>
                <p className="text-muted-foreground leading-relaxed">
                  The reflections generated by Luma are produced by artificial intelligence. 
                  While they are designed to be thoughtful and neutral, they:
                </p>
                <ul className="mt-4 space-y-2 text-muted-foreground">
                  <li className="flex items-start gap-3">
                    <span className="w-1.5 h-1.5 rounded-full bg-muted-foreground mt-2 flex-shrink-0" />
                    <span>May not accurately reflect your actual psychological state</span>
                  </li>
                  <li className="flex items-start gap-3">
                    <span className="w-1.5 h-1.5 rounded-full bg-muted-foreground mt-2 flex-shrink-0" />
                    <span>Should not be treated as authoritative or definitive</span>
                  </li>
                  <li className="flex items-start gap-3">
                    <span className="w-1.5 h-1.5 rounded-full bg-muted-foreground mt-2 flex-shrink-0" />
                    <span>Are interpretive descriptions, not psychological assessments</span>
                  </li>
                  <li className="flex items-start gap-3">
                    <span className="w-1.5 h-1.5 rounded-full bg-muted-foreground mt-2 flex-shrink-0" />
                    <span>May contain errors, biases, or inappropriate content</span>
                  </li>
                </ul>
              </div>

              <div>
                <h2 className="font-serif text-xl text-foreground mb-4">
                  Couple reflection
                </h2>
                <p className="text-muted-foreground leading-relaxed">
                  The couple reflection experience is intended for partners who wish to 
                  explore their relationship dynamics through reflection. It is not 
                  couples therapy or a substitute for professional relationship counseling. 
                  The shared reflections do not assess relationship health, predict outcomes, 
                  or provide guidance on relationship decisions.
                </p>
              </div>

              <div>
                <h2 className="font-serif text-xl text-foreground mb-4">
                  Crisis resources
                </h2>
                <p className="text-muted-foreground leading-relaxed">
                  If you are in crisis or experiencing thoughts of self-harm, please 
                  contact emergency services or a crisis helpline immediately:
                </p>
                <div className="mt-4 p-4 bg-secondary/30 rounded-sm">
                  <ul className="space-y-2 text-sm text-muted-foreground">
                    <li><strong className="text-foreground">US:</strong> 988 Suicide & Crisis Lifeline (call or text 988)</li>
                    <li><strong className="text-foreground">UK:</strong> Samaritans (116 123)</li>
                    <li><strong className="text-foreground">International:</strong> findahelpline.com</li>
                  </ul>
                </div>
              </div>

              <div>
                <h2 className="font-serif text-xl text-foreground mb-4">
                  Acceptance of terms
                </h2>
                <p className="text-muted-foreground leading-relaxed">
                  By using Luma, you acknowledge that you have read and understood this 
                  disclaimer, and that you accept the experience for what it is: a tool 
                  for gentle, non-clinical reflection — not therapy, diagnosis, or treatment.
                </p>
              </div>

              <div className="pt-8 border-t border-border">
                <p className="text-sm text-muted-foreground">
                  Last updated: March 2026
                </p>
              </div>
            </div>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  )
}
